# Generated by Django 3.1.7 on 2021-03-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glow_app', '0004_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glow_app.item'),
        ),
    ]
