# Generated by Django 3.1.7 on 2021-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow_app', '0005_review_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
