# Generated by Django 3.1.7 on 2021-05-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow_app', '0006_item_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
