# Generated by Django 3.1.7 on 2021-05-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glow_app', '0007_auto_20210504_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_price',
        ),
    ]
