# Generated by Django 3.1.7 on 2021-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow_app', '0008_remove_order_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
